### ISSUE TITLE
Feature Request - CTRL-A 'add host' change focus to new window

### ISSUE THREAD

**Issue by ronjcu** [R-Smith/vmPing#10]
First of all Fantastic tool!, very nicely done. 

As a feature request, would it be possible to change the input focus to the new window when using the 'Add Host' button, or CTRL-A? That way you can just starting entering the new address, hit enter and away it goes. I'm currently using the CTRL-A, shift-tab*2 to get to the new window and start entering.

Thanks.

**Comment by R-Smith** [comment]
That's something that has always bugged me.  I currently have it fixed and it'll be available in the next release.

**Comment by R-Smith** [comment]
This feature was added in version 1.2.7 and is now available for download.  It only auto changes focus if all of the existing ping windows have a hostname typed in.

**Comment by ronjcu** [comment]
Looks good Ryan, thanks.

BTW, the "Click here to download the latest .exe" is still pointing to 1.2.6.

**Comment by R-Smith** [comment]
It's all updated now to point to 1.2.7.  Thanks for letting me know.  I never would've noticed.
