### ISSUE TITLE
Issue when pinging invalid IP

### ISSUE THREAD

**Issue by ichantio** [R-Smith/vmPing#11]
Reproducible issue:
- Ping invalid IP such as 10. 
- Click STOP immediately after Ping start (this is crucial)
- The software will crash 100%
Windows 10 Enterprise Version 1709 Build 16299.611

I came across this by accident. I mistyped and then started the Ping too quickly, I then of course try to stop it too quickly. :)
Hope this help. This is a great tool.

**Comment by R-Smith** [comment]
Thank you for catching and submitting this bug report.  It was a simple divide by zero mistake in the statistic printout that was added a few versions back.  I pushed the fix, and it'll be in the next pre-compiled .exe download, which should be ready in a week.

**Comment by ichantio** [comment]
Thanks for fixing that so quickly. I introduced this tool to all of my colleagues. We find it an extremely useful tool. How do we buy you a cup of coffee? :)
I have a feature request, do I log another ticket?

**Comment by Nirad** [comment]
like i know yes. open another one

Le mar. 4 sept. 2018, à 18 h 09, ichantio <notifications@github.com> a
écrit :

**Comment by R-Smith** [comment]
This crash fix was added to v1.2.8 which is now available for download.
