### ISSUE TITLE
TCP port interval

### ISSUE THREAD

**Issue by Ack0** [R-Smith/vmPing#14]
Can you add an option to customize this interval? AFAIK this is fixed to 4sec minimum, but I need to monitoring a server with 1 sec interval.

Thanks in advance!

**Comment by R-Smith** [comment]
Yes, 4 seconds is currently the minimum.  I'll add the option for lower intervals in a future release.

**Comment by R-Smith** [comment]
This change was added to version 1.2.10.  The TCP port ping interval now goes below 4 seconds and is tied to your standard ping interval.  There may be an option in the future to specify different intervals for ICMP and TCP.
