### ISSUE TITLE
Loving VMPING

### ISSUE THREAD

**Issue by Gaffer2001** [R-Smith/vmPing#20]
I came across vmping about 3 months ago and it has totally changed the way we monitor some 500 devices. So far I run this application on an inverted 32" Screen and also various managers screens. We like to see the state of the entire fleet and also those systems not connecting to the net.
I get my current IP addresses from our database and I have cobbled together an excel file that I can export to the vmping.xml file and its working great
It there any way to pick up this file from our network so I only have to make one change per day for the non connecting systems .
My company is more than willing to pay for any development on this nifty application 
tonystorer@v-360.co.uk

**Comment by R-Smith** [comment]
Late response, but are you still interested?
