### ISSUE TITLE
Export and import Favorites sets

### ISSUE THREAD

**Issue by satan780** [R-Smith/vmPing#21]
How can I export of Favorites list and import it into another PC ?

**Comment by R-Smith** [comment]
The favorites and configuration data is stored in:  %LocalAppData%\vmPing\vmPing.xml

Just grab that file and copy it over to your other PC to the same location.  You'll have to create the vmPing folder if it doesn't already exist.

**Comment by satan780** [comment]
> The favorites and configuration data is stored in: %LocalAppData%\vmPing\vmPing.xml
> 
> Just grab that file and copy it over to your other PC to the same location. You'll have to create the vmPing folder if it doesn't already exist.

Thanks for helping me 👍

**Comment by hyperjojo** [comment]
hello,
first of all: Great Tool!!!
Would it be possible to define the path of this file? Then the tool would bei fully portable with the settings. Perfect for USB-Stick or cloud usage...
Thanks!
