### ISSUE TITLE
TCP Port Error

### ISSUE THREAD

**Issue by frmuses** [R-Smith/vmPing#22]
When we ping 3 servers using a text file for hosts, it allows us to create log files, but when we try to ping using a specific TCP port, it gives the following error as shown below. 

This is due to the “:” character in the ping call between the IP and the port (for example - www.google.com:1492).  In order to make this work, they would just need to include a character check and swap the “:” for a “_” or “-“, or swap the character they look for in their gui for an OS supported character.

![VMPing](https://user-images.githubusercontent.com/3237432/56963966-1d9f9a00-6b52-11e9-90cf-1a616c351e4f.png)

**Comment by R-Smith** [comment]
Good catch.  Fixed here https://github.com/R-Smith/vmPing/commit/f6df0493a2254f4002b652f0d2ad2dbc997628bc.  Invalid filename characters are now swapped with _.

The next release will include the patch.

**Comment by R-Smith** [comment]
The newly released v1.3.2 includes the patch.
