### ISSUE TITLE
Feature request: lowercase hostname option.

### ISSUE THREAD

**Issue by cmhamm** [R-Smith/vmPing#25]
This is an incredibly useful application, but I have a small, humble request. Technically, DNS hostnames are intended to be case _insensitive_. As such, it would be my preference to **not** capitalize hostnames by default. Typically when I see hostnames in all caps, it implies to me that it is NETBIOS, not DNS.

I downloaded the code, and I was able to remove all of the ToUpper methods easily enough, but I suspect that other people might like the uppercase setting. Obviously, this code was added for a reason; I am not so arrogant as to assume that everyone else would like it that way. Therefore, I thought it would make sense to add it as a configurable option, which is well beyond my ability to do. I am but a humble network engineer, not a developer. I looked at the code, tried to make changes so that I could contribute to the project, and quickly realized that this was over my head. :-)

I'd like to request a checkbox on the options page to prevent the application from changing everything to uppercase. That would apply to the Main window, FloodHost window, TraceRoute window, NewAlias window, as well as the command line parsing and the file parsing.

If it's helpful, I was able to remove uppercase references in the following files:

**Classes**

- Alias.cs (Edited Line 54)
- CommandLine.cs (Edited Line 92)

**Views**

- FloodHostWindow.xaml (Removed line 80)
- MainWindow.xaml (Removed line 509)
- MainWindow.xaml.cs (Edited lines 52 and 303)
- NewAliasWindow.xaml (Removed line 41)
- NewAliasWindow.xaml.cs (Edited line 48)
- TraceRouteWindow.xaml (Removed line 47)

I was able to compile and run the application with these changes, and I didn't notice any issues. I tested both the command line functionality as well as the host file functionality, and both worked without error.

Thank you for all of your work, and I appreciate the application.

**Comment by R-Smith** [comment]
Thanks. I'll take a look at adding an option to remove the forced ToUpper(). I'd like to re-do the Layout tab under the options window to give control over fonts and font sizes. I think that'd be a good spot to put the option. I might even just remove the ToUpper() entirely, I'll try running without it for a bit to see how it looks.

**Comment by R-Smith** [comment]
This is finally changed.  Edits are here: 8cd7d41fe32401e2b673fdabf962d4ccdd5b1308 and here: 69e652bb841f467bd212e4aa7cf4b829cc09b54b

Changes will be included in the next release. There's no configurable option for the setting. It instead doesn't force a character casing on you.
