### ISSUE TITLE
Feature Request: Test Email Notifications

### ISSUE THREAD

**Issue by bodagetta** [R-Smith/vmPing#26]
It would be a nice feature if vmPing could send a test email to verify SMTP credentials are correct.

**Comment by R-Smith** [comment]
This will be in the next release.

**Comment by R-Smith** [comment]
Added here 86954402248fa07de363be5f88fa5d384f764aab and here 9486f9fbe0c4cd97379b9dd79eda87789b83d7ab

This feature is included with release 1.3.3.
