### ISSUE TITLE
Failing to log status changes

### ISSUE THREAD

**Issue by Sola1991** [R-Smith/vmPing#27]
Dear @R-Smith, 
I like your app. it's light and easy to use but I'm facing an issue whenever I tried to log status changes.
I've tried changing the file name/ the file location / run as administrator but the same error will pop up after logging 1-2 lines in the file and the logging will be disabled (depending on the number of pinged servers).

Attached a photo of the error msg
![Capture20082019](https://user-images.githubusercontent.com/16246457/63372610-20d3c580-c38f-11e9-9208-3b7788832834.PNG)

btw, I'm running on win10

Please let me know if you need me to share some data.
Appreciate your assistance  
Thanks,

**Comment by R-Smith** [comment]
Do you have the .txt file open in Excel or similar application?  Excel puts a lock on the file that will cause writes from vmPing to fail.  At this time, vmPing doesn't attempt to check for a filesystem lock - it just reports an error when it attempts to write but fails.

**Comment by Sola1991** [comment]
no. I only open the files after the error pop up. 
this only happen the status change file. the ping output files are fine.
I've tried to delete the file/change the file name/location to avoid having another app being using it but the same error will pop up every time.

**Comment by R-Smith** [comment]
Ok, I think I know what's causing the issue.  Do you have multiple hosts changing status at the same time?  That would cause the write error with the approach I'm using.  I'll come up with a better solution in the next few weeks.

**Comment by Sola1991** [comment]
yes, I've 3 hosts. 
the change in status is happening because my ISP is not reliable :(
so all of the 3 hosts will change status ,relatively, at same time
Thanks,

**Comment by R-Smith** [comment]
Fixed here - 35b6c9f6008282303ff8750dededfd6da8e90f5b
This will be included in the next release.

**Comment by R-Smith** [comment]
This bug fix is included in release 1.3.3.

**Comment by Sola1991** [comment]
Hi @R-Smith 
I've been using the new update for a week now; It's working like a charm.
Thank you for your efforts,
Best Regards,
