### ISSUE TITLE
Option to change number of lost pings before failure

### ISSUE THREAD

**Issue by mdaviesnz** [R-Smith/vmPing#3]
I'd like to request an option be added so that it's possible to configure the tool to wait until X number of consecutive pings are lost before a failure is notified. 

It could still turn the ping window red, or perhaps an intermediate colour like yellow to indicate a warning situation, when packets are lost within the threshold but it wouldn't pop up a notification (or email) until the certain number of pings are lost. 

This is my only gripe with the tool because I find that when I have some intermittent packets lost it creates a lot of spurious HOST is down notifications.

**Comment by R-Smith** [comment]
I am redoing the options window to give more control over application settings.  In the new options window I will include an alert threshold.

**Comment by R-Smith** [comment]
An alerts threshold option is included in version 1.1.12.  Notifications are not triggered until the specified number of consecutive pings are lost.  The probe window changes from green to a yellow color if packets are lost, but below the alert threshold.  The default value is two and can be configured from the options window.  In the future, I will add the ability to have the application remember custom default values.

**Comment by mdaviesnz** [comment]
Nice one Ryan, this is ideal, works well!
