### ISSUE TITLE
Aliases not loaded when executed with hostname file

### ISSUE THREAD

**Issue by MeatyFresh** [R-Smith/vmPing#30]
When vmPing is loaded with a list of hosts to ping, any previously set aliases are loaded and displayed on the interface in the top left of each ping window. If you instead load the lists of hosts from a file (as introduced in 1.3.1) then these aliases are not shown. If you open Manage Aliases window and close it again, the aliases appear.

**Comment by R-Smith** [comment]
Interesting.  Thanks for the report.  This will be fixed in the next update.

**Comment by R-Smith** [comment]
Fixed here - 0e6d3423c6d98c855906bc86a38f3e69d570c17f
It'll be in the next release.

**Comment by R-Smith** [comment]
This bug fix is included in release 1.3.3.
