### ISSUE TITLE
Edit button has no effect

### ISSUE THREAD

**Issue by fxnn** [R-Smith/vmPing#34]
How am I supposed to configure the hostname to ping? Pressing a host's edit button doesn't do anything; whereas the "open separate window" and "close" buttons actually work.

Thanks in advance :)

P.S.: Couldn't find info about this in README or closed issues.

**Comment by fxnn** [comment]
Oh, by chance I saw the text editing cursor when moving the mouse above the white field. I'd suggest some hint, e.g. a watermark-style text saying "(no hostname set)" or the like.

**Comment by 9swampy** [comment]
Same problem; thanks for posting your discovery.  Definitely agree with the proposal...

**Comment by hazymat** [comment]
Although this didn't confuse me as a new user, I agree it is a worthwhile if tiny enhancement.

**Comment by R-Smith** [comment]
Fixed here: 93ccd187835f2a0c4e05af0adf56d7cb2d66c743 and here: 9edb7de4b31bda90143257ea5ea2122e5df7f83d

The hostname textbox now has a subtle placeholder text that says "Enter a hostname". Placeholder text shows if the textbox has focus and no hostname is entered.

The 'Edit Alias' button at the top of each probe window is now disabled and grayed out if no hostname is entered.

Changes will be included in the next release.
