### ISSUE TITLE
[Feature Request]: Option to auto-dismiss Popup Notifications

### ISSUE THREAD

**Issue by amard33p** [R-Smith/vmPing#39]

**Comment by vtainc** [comment]
+1

**Comment by hazymat** [comment]
+1

**Comment by R-Smith** [comment]
This was added here: fbea3aa33de673bfdff8110c56cdce10877399a4, here: c326cf863fbd8d14c40e835823f1a914d8356e53, here: 0d81e07de662fa3495086083ca70033e06e6929a, and here: 245d843b3bf36701cc41aa77e9767ebb4a0ab580

The changes are available now in release 1.3.8.
