### ISSUE TITLE
[Feature Request]: create favorites set by importing from file

### ISSUE THREAD

**Issue by wanccie** [R-Smith/vmPing#40]
It would be nice to be able to create a favorites set directly in the GUI by importing from a hosts file. Currently, there are two indirect ways to make a favorite set from a list of hosts:

- start `vmPing` from the command line to use the hosts file, and then save that layout to your favorites
- reformat your hosts as an XML file, which is annoying to do manually

It would be convenient to be able to create the favorites list directly by importing a file with the same format as you would invoke it from the command line.

**Comment by R-Smith** [comment]
Added here: 655b132ce19bd199959799f6a8471b90cfe72de6, here: d3bd14e650c024d385db055bd99768ffdc95c505, here: ad9d27351443dbda1723c22b4ff3ad75dcafa4a8, here: ffd85a46a2b19c9e290cd9e1d891e964b3cafe7e, and here: a8752722ae9430ad91a7e1bb574d89cb83dc6421

This will be included in the next release. The 'new' and 'edit' favorite windows now give a multi-line text box, so you can just paste your hosts right into the textbox. Hosts can be entered one per line, comma-delimited, or a combination of commas/newlines.

**Comment by wanccie** [comment]
Hi Ryan,
Awesome!!  The update works great.  Perfect, no more command line to input ips... just paste my ips or names into the window. 
Thanks again.

**Comment by R-Smith** [comment]
Latest version now lets you drag & drop a text file onto the window as well.

**Comment by wanccie** [comment]
WOW... thanks again that will be awesome.

Lloyd
