### ISSUE TITLE
Popup Notifications - Save Settings

### ISSUE THREAD

**Issue by simonabraham** [R-Smith/vmPing#41]
Hello,

First of all thank you for vmPing!  Excellent ping software.  Is there a way of saving popup notifications settings so that when you start the application, it's default on "Never" or anything you want it to be?

Thanks for a quick answer :-)

**Comment by vtainc** [comment]
+1

**Comment by R-Smith** [comment]
Hey there.  I didn't realize I wasn't saving that option.  Should be fixed in the next version.

**Comment by simonabraham** [comment]
Thanks so much!

**Comment by Kyr4l** [comment]
hi i love your program but it's still not fixed

**Comment by R-Smith** [comment]
Add here: 6a19572db6b90ea37404718bea4613100acea016, here: 3b3eca7b7242adc14ceadc82a28f09a1af0bb28e, and here: a3564d6f633ec0672fe6b12adaccb63807be6303

This will be included in the next release.

**Comment by R-Smith** [comment]
The changes are now available in release 1.3.8.
