### ISSUE TITLE
Feature request: Label in notifications

### ISSUE THREAD

**Issue by Dubz** [R-Smith/vmPing#43]
Simple request. Sometimes I'm monitoring multiple sites for issues. This is a great tool to use, as I typically have to monitor some for hours.

What I'd like is to have the option to toggle notifications between their IP/host[:port] and their label added at the top. When I'm pinging multiple sites, I have to open up that instance to see which is the one dropping, and sometimes locate that specific device (some sites I might only monitor 2 things, others I monitor 12. Depends on the issue).

Ideally, I'd like to have notifications show labels, but history still show IP[:port] for screenshots. I believe both should be configurable though, based on the user's personal preference and use case.

**Comment by R-Smith** [comment]
Yeah for sure, the history and notification popups should all show the aliases.  It should be fixed in the next version.

**Comment by Dubz** [comment]
I still believe they should each be optional, in case you weren't considering that. Just my two cents, as I know some people may want one or the other to show a certain way.

**Comment by R-Smith** [comment]
Added here 436e99e67b5ecd5868bd20c4f10e0dcb91380c8e and here f7c1cefa5807795ea36f4160436f3c61b5313561
This will be included in the next release. For the popup notification, only the host alias is shown (if set). If you bring up the full status history window it'll show both host/ip and alias (if set). Same for email alerts. No toggle.

**Comment by R-Smith** [comment]
The changes are now available in release 1.3.8.
