### ISSUE TITLE
no always on top?

### ISSUE THREAD

**Issue by werdegars** [R-Smith/vmPing#44]
i suggest make this apps enable always on top feature

**Comment by werdegars** [comment]
also how to ping WAN?

**Comment by An-dir** [comment]
the "enable always on top feature" is already documented in the integrated help (press f1) but i can not find it either. Searched sourcecode for "ApplicationOptions" and did't get any information if it's possible to be enabled via xml only. Maybe it is already planned to be implemented.
I'm also waiting to be able to keep mainwindow always on top


what do you mean with "also how to ping WAN?" every feature request issue should be a seperate issue.

**Comment by R-Smith** [comment]
There was previously an always on top setting, but I removed it a while back due to some other UI changes.  I'll bring it back in.

**Comment by R-Smith** [comment]
Add here 73ec48f14cae9b683b377cd70d712961c929e407
Available in release 1.3.20
