### ISSUE TITLE
Feature request: ability to group sets of addresses

### ISSUE THREAD

**Issue by travbro** [R-Smith/vmPing#46]
Could you create Ping sub folders / Icon  I.E. allow several sets to be running under folders / Icons /  if one device goes out of ping under the folder, the set icon would reflect the status change...  thanks for allowing this request.

**Comment by R-Smith** [comment]
Hi, thanks for your request. I don't see myself using a feature like this and would be time consuming to implement. I'm planning an alternate compact view for the main interface and can maybe revisit this once that's added.
