### ISSUE TITLE
play a sound when ip is up

### ISSUE THREAD

**Issue by alain2208** [R-Smith/vmPing#47]
Hi great job and like the play sound when ip goes dead but could also be good to play a distinct one when an ip is back. 

I'm using it to supervise long install with multiple reboot and virtual ip activation that would be good to have this 'is up' and not only the 'is down'
thanks

**Comment by R-Smith** [comment]
Added here a74d68c6848979e46b7488714ccc8f470672af9d, here 6fb10fa017a097df96c6f03456a0f4ad7a9fc5d9, here 106eaa9fb8d25a6cbd9478b315cf3fd9241fbeca, and here 839f0edaeb5dd7b4fb6b29c88c1da7af66697e4b

This will be included in the next release.

**Comment by R-Smith** [comment]
The changes are now available in release 1.3.8.
