### ISSUE TITLE
START FROM LAST LAYOUT 

### ISSUE THREAD

**Issue by arianks** [R-Smith/vmPing#48]
It's possible to configure this app to start from last saved layout or to select from which layout to start.

**Comment by R-Smith** [comment]
This feature is planned.

**Comment by R-Smith** [comment]
Added here: 33a818c027fe0afeecb8ec2cd5495f8b837dcd2e, here: 7e589a30c00b0566d360efd38867eae255a22005, and here: 42847f7803cf5f5d934e2152a0375a7cfc64be86.

No option to start from last layout, but you can start from a favorite or customize a few things with how it starts. Seems to work well. Available now in v1.3.15.
