### ISSUE TITLE
Show Alias in alerts / status history

### ISSUE THREAD

**Issue by hazymat** [R-Smith/vmPing#49]
Desktop notification and Status history refer to hosts by their IP address.

I think a good enhancement would be to refer to them with both IP and Alias if applicable, e.g.

[datetime] 10.1.1.1 (Gateway) is DOWN

Of course, if no Alias is set, then it would show just the IP address.

Same goes for Status History window and email alerts (I haven't tested the latter, sorry if it already does this)

**Comment by R-Smith** [comment]
Added here 436e99e67b5ecd5868bd20c4f10e0dcb91380c8e and here f7c1cefa5807795ea36f4160436f3c61b5313561
This will be included in the next release. For the popup notification, only the host alias is shown (if set). If you bring up the full status history window it'll show both host/ip and alias (if set). Same for email alerts.

**Comment by R-Smith** [comment]
The changes are now available in release 1.3.8.
