### ISSUE TITLE
Show IP address when pinging an hostname not answering

### ISSUE THREAD

**Issue by Meganono** [R-Smith/vmPing#5]
Hello,

Could you add resolved IP address when pinging an hostname and request time out.

Now :

*** Pinging XXXXXXX :
[aa:bb:cc]  Request timed out.

With IP address :

*** Pinging XXXXXXX (IP address) :
[aa:bb:cc]  Request timed out.

Thanks

**Comment by R-Smith** [comment]
I agree that the resolved IP should always print.  The feature has been added in version 1.1.14.
