### ISSUE TITLE
feature request: allow select+copy to clipboard

### ISSUE THREAD

**Issue by stuntsman** [R-Smith/vmPing#50]
It'd be handy to be able to select text+copy to the clipboard from the log panels. It's much more cumbersome to find the log txt first just to share a few rows with others.

**Comment by SupraOva** [comment]
+1

**Comment by R-Smith** [comment]
This feature is planned.

**Comment by R-Smith** [comment]
I started testing this feature. If you get v1.3.15, it's added to the isolated ping window (hover over a ping window to get the mini title bar, which has the open isolated view button).  One problem I'm having is if you are highlighting text from right to left, your highlight gets reset every time the ping window updates. I don't think there's any way to fix that. Highlighting text from left to right works fine. The other problem I'm having is the output auto-scrolls to the bottom on each update, so it's difficult to highlight text. This should be fixable. And this is only when active. If it's stopped, highlighting works as expected.

**Comment by SupraOva** [comment]
Thank you ! I will try it

**Comment by R-Smith** [comment]
Added here 59537f481a96a9e26fdd0b3f15137d06ee9c0f6e and here 7fbeae6f36560b91eb6d4bbeeed5e79e9cc43e24. Available in release 1.3.16.
