### ISSUE TITLE
Crash when pinging a port on an IPv6 host

### ISSUE THREAD

**Issue by craigo-** [R-Smith/vmPing#51]
When attempting to contact a host on a specific port, e.g. hostname:80, and the hostname resolves to an IPv6 address, vmPing crashes to desktop.

Wrapping the IPv6 address in square brackets and appending the port (as per [RFC3986](https://www.ietf.org/rfc/rfc3986.txt)), e.g. [ipv6Addr]:80, results in the message "Unable to resolve hostname".

Sending a regular ICMP ping to the hostname or the IPv6 address (via vmPing or command line), works as expected. Using vmPing to connect to an IPv4 address on port 80 also works as expected.

vmPing 1.3.4, Windows 10 Enterprise 20H2 x64

**Comment by R-Smith** [comment]
Hey, I'll definitely take care of this. Hopefully within the next few weeks.

**Comment by R-Smith** [comment]
Fixed here: debe86d4459d83e1126e3f606091ea7b677fbd54
This will be included in the next release.

**Comment by R-Smith** [comment]
The changes are now available in release 1.3.8.
