### ISSUE TITLE
List "Input Address F2" should be prefilled with current pings (enhancement)

### ISSUE THREAD

**Issue by An-dir** [R-Smith/vmPing#57]
List "Input Address F2" should be prefilled with currently running/configured Pings and might be called "List Edit Mode F2" or "Bulk edit F2" or something else that would fit better then.

**Comment by R-Smith** [comment]
Good suggestion.  Added here: 0ef7f050129099a7e6356dae4a2d62b17326e1ba
I'll think about the rename

**Comment by R-Smith** [comment]
Available in release 1.3.15
