### ISSUE TITLE
Ping doesn't restart after reconnection (or laptop coming back from sleep)

### ISSUE THREAD

**Issue by hazymat** [R-Smith/vmPing#62]
**Current behaviour**
If you disconnect and reconnect the network adapter (or change network settings, put laptop to sleep, run out of wireless signal etc.), ping stops. You have to manually restart ping by pressing the button.

**Suggestion for enhancement**
The desired behaviour would be that vmPing ONLY stops pinging when I press the stop button. This means it would attempt to ping even when the network adapter is disconnected, and continue after it is reconnected.

This is the standard behaviour for command line ping, and it's useful because if you close your laptop, change your TCP/IP settings then change them back, or just lose signal, it will resume once the connection is back.

To demonstrate, I started a ping from command line AND vmPing, then disconnected then reconnected my wireless. You can see from the first screenshot that ping continues with command line, and second screenshot shows that in vmPing, ping stops and you would need to press the "ping" button to start it up again.

![image](https://user-images.githubusercontent.com/7063284/113581639-4fafb580-961f-11eb-8ed7-c106abed5297.png)

![image](https://user-images.githubusercontent.com/7063284/113581800-84bc0800-961f-11eb-888f-1285a877fac5.png)

**Comment by R-Smith** [comment]
Yes, it should keep pinging. I'll change this for the next release.

**Comment by R-Smith** [comment]
Changed here: 6f6b0c07776745ec56a88abd99ad42c554e66b69

Included in version 1.3.17
