### ISSUE TITLE
Feature Request: Continue ping on fails

### ISSUE THREAD

**Issue by Dubz** [R-Smith/vmPing#66]
I want to utilize this in a monitoring setting, however I noticed sometimes the pings cease entirely if there is an error reported. Specifically if the network connection goes out. Just want it to be able to self resurrect and not require intervention.

Thanks!

**Comment by R-Smith** [comment]
This will be fixed in the next release.

**Comment by R-Smith** [comment]
Changed here: 6f6b0c07776745ec56a88abd99ad42c554e66b69

Included in version 1.3.17
