### ISSUE TITLE
vmping 1.3.16 stop working after click status history

### ISSUE THREAD

**Issue by racoencmderror** [R-Smith/vmPing#68]
today I tried the latest version of vmping (1.3.16) but every time I press the history status, the application always force close

![vmping-stop working](https://user-images.githubusercontent.com/86336192/124221777-97fd4780-db2a-11eb-8756-8e1f8bcd5f60.png)

![vmping-stop working-2](https://user-images.githubusercontent.com/86336192/124221928-df83d380-db2a-11eb-9742-4763394358a8.png)

**Comment by R-Smith** [comment]
Looks like you're on win 7. I think I see the problem. Do you get the same crash when opening the options window?

**Comment by R-Smith** [comment]
I think the problem is fixed here 45e537e8e8eab2b73d971da3c89e01838cd4829b
Are you able to compile / run from the latest source?  If not, I'll see if I can attach a binary.

**Comment by racoencmderror** [comment]
thank you very much, currently the application is running well
![stable](https://user-images.githubusercontent.com/86336192/124410630-164d2a00-dd75-11eb-9736-5eb444d1c30e.png)
