### ISSUE TITLE
Favorities on startup

### ISSUE THREAD

**Issue by djradeesek** [R-Smith/vmPing#69]
Is possible run with some parameters for select one of favorities? I need run on start of Windows for monitoring more pings. I have created list of IPs and saved in favorities.
Thank You! ;)

**Comment by R-Smith** [comment]
Yes, bring up the options then look at the General tab under Startup. Select the option to load a favorite. This will auto load the favorite set you choose when vmPing opens. Be sure to check Save as defaults as well.
