### ISSUE TITLE
vmping crashes

### ISSUE THREAD

**Issue by dnyt84** [R-Smith/vmPing#70]
Hello,

when open vmping I can add the IP but then it crashes shortly after.
This is what I find in event viewer:

Application: vmPing (2).exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at System.Windows.Media.Composition.DUCE+Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean, System.Nullable`1<ChannelSet>)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr)
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Faulting application name: vmPing (2).exe, version: 1.3.17.0, time stamp: 0x60e61fce
Faulting module name: KERNELBASE.dll, version: 10.0.19041.964, time stamp: 0x812662a7
Exception code: 0xe0434352
Fault offset: 0x0000000000034b89
Faulting process id: 0x7a80
Faulting application start time: 0x01d784c69badb4a3
Faulting application path: C:\Users\xxx\Downloads\vmPing (2).exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 73eb679a-0d7c-48cc-bf9b-82dbccf83397
Faulting package full name: 
Faulting package-relative application ID: 

Let me know what else you need to troubleshoot this.

Thank you!

Daniel

**Comment by boxgage** [comment]
Me pasa igual en la ultima version lanzada, deja de enviar ping después de un momento, por otra parte en la opción de configuracion donde sale el TTL y packet data size cuando se cambian esos valores se estropea el archivo con lo que tenga dentro,

**Comment by R-Smith** [comment]
Interesting error. I'm not seeing where this would be happening. A few questions:
Are you doing standard ICMP pings or TCP pings?
Will it crash with just a single ping going, or do you need a few running for it to crash?
Do you have text logging or audio alerts turned on?
Is it possibly crashing when a ping is lost or when a host goes down or up?
Which OS are you on and do you know if you have any .NET frameworks installed that aren't already included with your OS?

There is one change I introduced in 1.3.17 where it continues to attempt pings on errors and I'm suspecting it has to do with that. Can you try release 1.3.16 and see if it crashes for you?

**Comment by boxgage** [comment]
![image](https://user-images.githubusercontent.com/88375674/128141288-0cca838a-368f-4875-bc84-2430fa0ed903.png)


Adjunto Imagen de como hago Ping, después de cierta cantidad de ping enviados se detiene se bloquea y solo queda cerrar para volver a comenzar, ocurre en la Versión 1.3.17

¿Está haciendo pings ICMP estándar o pings TCP?
Re: Estándar

¿Tiene activado el registro de texto o las alertas de audio?
Antes de que preguntaras inactivo en ambos

¿Es posible que se bloquee cuando se pierde un ping o cuando un host falla o sube?
E visto perdida de paquetes pero no es así cuando se bloquea, por lo menos no lo tengo del todo claro.


¿En qué sistema operativo estás y sabes si tienes algún marco .NET instalado que no esté incluido en tu sistema operativo?
Windows 10 x64 build 21H1 actualizado. comparte las version .NET instaladas en mi PC
![image](https://user-images.githubusercontent.com/88375674/128142216-d787885d-48ce-44af-b66b-4bf2abcdf91d.png)

**Comment by boxgage** [comment]
Acabo de probar la versión 1.3.16 con la misma configuración usada en la versión 1.3.17 y ocurre lo mismo se bloquea el ping y la ventana por completo, yo uso el formato portable y vendría siendo la misma que uso en la  1.3.15 versión en la cual no falla.   como detalle a resaltar en la Versión  1.3.16 y 17 se bloquea por completo la ventana no permite ni cerrar ni minimizar ni maximizar, solo desde la barra de tareas o desde el administrador de tareas permite cerrarla.

**Comment by R-Smith** [comment]
Sorry for the late response.  Just to clarify:

1.3.17 = crash
1.3.16 = crash
1.3.15 = good

Is that correct?

**Comment by boxgage** [comment]
Correcto

**Comment by R-Smith** [comment]
Can you try this version?
[vmPing.zip](https://github.com/R-Smith/vmPing/files/7102026/vmPing.zip)

**Comment by R-Smith** [comment]
Here's the commit for the test version if you want to review and run from source:
https://github.com/R-Smith/vmPing/commit/41e81b7096382257d881ea098415a3fcd27a2d5f
I changed the area that prints the ping output from textboxes back to listboxes

**Comment by boxgage** [comment]
Estoy probando el .Zip que me enviaste con los mismos parámetros  anteriores.

**Comment by boxgage** [comment]
he finalizado las pruebas en ese .Zip adjunto y ese si funciona perfecto sin bloqueos y no presento ningún tipo de falla.


![image](https://user-images.githubusercontent.com/88375674/132112534-29cc97e8-2593-4eab-a013-e772bf0ef619.png)

**Comment by R-Smith** [comment]
Fixed here: 41e81b7096382257d881ea098415a3fcd27a2d5f

Available in release 1.3.18. Gracias!
