### ISSUE TITLE
Feature request - option to save stats to a csv file

### ISSUE THREAD

**Issue by wanccie** [R-Smith/vmPing#71]
The new version with the stats (F12) is awesome.  Is it possible to save that F12 table to a csv file?  Thanks in advance.

**Comment by wanccie** [comment]
You're great.  Thanks again for your continued support.
Lloyd Prindle

**Comment by R-Smith** [comment]
Add here 6f70842c5be68909cf3808e6d2787525e086a75c
This will be included in the next release.

**Comment by R-Smith** [comment]
Available now in release 1.3.19.
