### ISSUE TITLE
vmPing hangs after windows screen off

### ISSUE THREAD

**Issue by vtainc** [R-Smith/vmPing#72]
vmPing hangs after some period of inactivity. Windows turns off the screen on my computer after 10 minutes of inactivity ( without system standby, only screen off ) after this when i move the mouse and login to the system i see, that vmpings does not respond to mouse and keyboard and consumes big amount of cpu usage

w10pro build 19043.1165

![image](https://user-images.githubusercontent.com/19706430/131337879-81fa9d7f-30b3-4eec-96fa-640ed5216593.png)

last version, that I have used 1.3.12 does not have such problems.

**Comment by R-Smith** [comment]
Interesting. This might be related to issue #70. Would you happen to have any versions of the .NET framework installed that aren't already included with Win 10?

**Comment by vtainc** [comment]
HI, I have only these versions installed:

![image](https://user-images.githubusercontent.com/19706430/131961463-f1dedf74-faab-4922-acd0-1643f425e97f.png)

**Comment by R-Smith** [comment]
Can you try the .zip I posted on issue #70 and see if that version fixes the problem? I also posted the commit if you prefer to run from source.

**Comment by vtainc** [comment]
Yes, version mentioned in issue #70 works fine.

**Comment by R-Smith** [comment]
Fixed here 41e81b7096382257d881ea098415a3fcd27a2d5f

Available in release 1.3.18
