### ISSUE TITLE
Error in Processing

### ISSUE THREAD

**Issue by orcannus** [R-Smith/vmPing#73]
Error in processing. The server response was 5.7.3 STARTTLS is required to send mail 
Util.cs smtpClient ... 
Added EnableSSL = true and = false 
Still same results? 

smtp requirements:
Server: smtp.office365.com
Port: 587
Encryption: STARTTLS

**Comment by R-Smith** [comment]
It looks like I need to add an option for enabling STARTTLS. I'll put this in the next release as a checkbox next to the port field.

**Comment by R-Smith** [comment]
Added here: 8a2e5535b9bac75570ab19063eea2217cf86a26a

Available in release 1.3.18
