### ISSUE TITLE
Feature request - Source Address

### ISSUE THREAD

**Issue by guitarxan** [R-Smith/vmPing#74]
Is is possible to add a feature akin to the "-S srcaddr     Source address to use." parameter in ping.exe?
Sometimes the OS get's confused which NIC to use, etc

Cheers

**Comment by R-Smith** [comment]
Unfortunately the .NET framework that this application is built on does not support specifying a source address. There is an open issue on the .NET GitHub here https://github.com/dotnet/runtime/issues/29248. I can implement if it ever gets added.
