### ISSUE TITLE
IP change problem

### ISSUE THREAD

**Issue by djmar33** [R-Smith/vmPing#76]
Why does Ping a domain name keep changing IP?
and
ping 114.114.114.114 display timeout，but It is normal to use the Ping tool provided by win

**Comment by R-Smith** [comment]
When pinging by a DNS name, vmPing continues to perform DNS lookups while it is actively pinging the host. This means that the IP address vmPing is targeting could change if the DNS resolution changes.

Host 114.114.114.114 is unusual. It is not properly responding to certain ICMP requests. This can be observed in Wireshark. The ICMP packets it's returning has the incorrect checksum bits which results in Windows dropping the packet. This is not a problem with vmPing. I was able to get valid responses by adjusting the packet data size in vmPing. Bring up Options -> Advanced -> Packet data size - and set it to 32, the host then returns a valid reply.
