### ISSUE TITLE
Vmping error message

### ISSUE THREAD

**Issue by racoencmderror** [R-Smith/vmPing#77]
Dear Vmping team, I want to inform you that an error message appears

![vmping-error](https://user-images.githubusercontent.com/86336192/144389223-d2a11a35-38d6-4919-9b99-0fa6f9067200.png)

**Comment by An-dir** [comment]
Hi, 
open explorer and enter the path: %localappdata%\vmPing\
rename "vmPing.xml" file and see if it solves the issue. If yes, take a look at the content. If you can't fix it on you own you may want to share it with us.
If renaming does not remove the error message, look next to your vmPing.exe file if you have the xml file there, and try renaming and reading/fixin/posting it...

**Comment by racoencmderror** [comment]
> Hi, open explorer and enter the path: %localappdata%\vmPing rename "vmPing.xml" file and see if it solves the issue. If yes, take a look at the content. If you can't fix it on you own you may want to share it with us. If renaming does not remove the error message, look next to your vmPing.exe file if you have the xml file there, and try renaming and reading/fixin/posting it...

thank you for the help, I have practiced it, it works well
