### ISSUE TITLE
Feature Request - ping forever

### ISSUE THREAD

**Issue by Klopot** [R-Smith/vmPing#82]
Hello,
would it be possible to add option, so that vmping wouldn't stop pinging even if there are connection errors/lack of response from hosts ?
Just like "ping -t"  - tries pinging forever, which is useful while monitoring network.
Regards
PK

**Comment by R-Smith** [comment]
This is the default behavior starting on release 1.3.17. What version are you on? If you're on the latest release, what error are you seeing that causes the pings to stop?

**Comment by R-Smith** [comment]
Awesome! Glad it's working.
