### ISSUE TITLE
show simple statistics of the lagency

### ISSUE THREAD

**Issue by betterdoitnow** [R-Smith/vmPing#9]
after we stop the ping, can it show an simple statistics? like below, 

Ping statistics for 1.1.1.1:443
     4 probes sent.
     4 successful, 0 failed.  (0.00% fail)
Approximate trip times in milli-seconds:
     Minimum = 46.118ms, Maximum = 50.793ms, Average = 48.064ms

**Comment by R-Smith** [comment]
That was a great idea.  I added it to version 1.2.5 available now.
